#!/usr/bin/env php
<?php

namespace Nooku;

// Run the class from request if the script is called directly from the command line
if (!count(debug_backtrace())) {
    Installer::fromInput($argv);
}

class Installer
{
    public static $files = array(
        'install.sql', 'views.sql', 'users.sql'
    );

    public $task;
    public $database = 'v2_9999';
    public $www = '/var/www/police.dev';

    public function __construct($task)
    {
        if (!in_array($task, array('install', 'reinstall'))) {
            throw new \InvalidArgumentException('Invalid task: '.$task);
        }

        $this->task = $task;
    }

    public static function fromInput($argv)
    {
        $task = isset($argv[1]) ? $argv[1] : '';

        $instance = new self($task);
        $instance->run();
    }

    public function run()
    {
        try {
            $this->precheck();

            $task = $this->task;
            $this->$task();
        }
        catch (\Exception $e) {
            $this->error($e->getMessage());
        }
    }

    public function install()
    {
        $this->createDatabase();
        $this->createMultisite();
        $this->modifyConfiguration();
        $this->runComposer();
        $this->runPhpmig();
    }

    public function uninstall()
    {
        $this->deleteDatabase();
    }

    public function reinstall()
    {
        $this->uninstall();
        $this->install();
    }

    public function precheck()
    {
    }

    public function createMultisite()
    {
        $template = <<<EOF
<?php
class JSiteConfig extends JConfig
{
	var \$theme = 'mobile';
	var \$site = '9999';
}
EOF;

        $dir = $this->www.'/sites/9999/config';
        if (!is_dir($dir)) {
            mkdir($dir, 0777, true);
        }

        file_put_contents($dir.'/config.php', $template);
    }

    public function createDatabase()
    {
        $result = `echo 'SHOW DATABASES LIKE "$this->database"' | mysql -uroot -proot`;
        if (!empty($result))
        {
            $this->out("Database table exists.\nRun 'police reinstall' if you would like to re-create it");

            return;
        }

        $result = shell_exec("echo 'CREATE DATABASE `$this->database` CHARACTER SET utf8' | mysql -uroot -proot");
        if (!empty($result)) { // MySQL returned an error
            throw new \Exception(sprintf('Cannot create database %s. Error: %s', $this->database, $result));
        }

        $dir = $this->www.'/install/custom/mysql';

        foreach (self::$files as $file)
        {
            $result = `mysql -proot -uroot $this->database < $dir/$file`;
            if (!empty($result)) { // MySQL returned an error
                throw new \Exception(sprintf('Cannot import file %s. Error: %s', $file, $result));
            }
        }
    }

    public function deleteDatabase()
    {
        $result = shell_exec("echo 'DROP DATABASE IF EXISTS `$this->database`' | mysql -uroot -proot");
        if (!empty($result)) { // MySQL returned an error
            throw new \Exception(sprintf('Cannot delete database %s. Error: %s', $this->database, $result));
        }
    }

    public function modifyConfiguration()
    {
        $input    = $this->www.'/config/config.php-dist';
        $output   = $this->www.'/config/config.php';

        $contents = file_get_contents($input);
        $replace  = function($name, $value) use(&$contents) {
            $pattern     = sprintf("#%s = '.*?'#", $name);
            $replacement = sprintf("%s = '%s'", $name, $value);

            $contents = preg_replace($pattern, $replacement, $contents);
        };

        $replace('sendmail', '/usr/bin/env catchmail');
        $replace('theme', 'splash');
        $replace('user', 'root');
        $replace('password', 'root');
        $replace('db', $this->database);

        file_put_contents($output, $contents);
        chmod($output, 0644);
    }

    public function runComposer()
    {
        $this->out('Installing dependencies via Composer');
        $output = `cd $this->www/install/custom; composer --no-interaction install`;
    }

    public function runPhpmig()
    {
        $this->out('Installing Phpmig dependencies via Composer');
        $output = `cd $this->www/scripts/phpmig; composer --no-interaction install`;

        $config = $this->www.'/scripts/phpmig/config.php';
        if(!file_exists($config))
        {
            $contents = file_get_contents($this->www.'/scripts/phpmig/config.php-example');
            $contents = preg_replace('/\$this\->host = \$config\->host/', "\$this->host = '192.168.52.10'", $contents);

            file_put_contents($config, $contents);
            chmod($config, 0644);
        }

        $this->out('Executing Phpmig migrations');
        $output = `cd $this->www/scripts/phpmig; bin/phpmig migrate`;
    }

    public function out($text = '', $nl = true)
    {
        fwrite(STDOUT, $text . ($nl ? "\n" : null));

        return $this;
    }

    public function error($text = '', $nl = true)
    {
        fwrite(STDERR, $text . ($nl ? "\n" : null));

        return $this;
    }
}